[package]
name = "ruff"
version = "0.0.44"
edition = "2021"

[lib]
name = "ruff"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.83"
anyhow = { version = "1.0.60" }
chrono = { version = "0.4.21" }
fern = { version = "0.6.1" }
filetime = { version = "0.2.17" }
glob = { version = "0.3.0" }
itertools = { version = "0.10.3" }
log = { version = "0.4.17" }
once_cell = { version = "1.13.1" }
rayon = { version = "1.5.3" }
regex = { version = "1.6.0" }
rustpython-parser = { features = ["lalrpop"], git = "https://github.com/charliermarsh/RustPython.git", rev = "7d21c6923a506e79cc041708d83cef925efd33f4" }
serde = { version = "1.0.143", features = ["derive"] }
serde_json = { version = "1.0.83" }
toml = { version = "0.5.9" }

[dev-dependencies]
insta = { version = "1.19.1", features = ["yaml"] }

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1
opt-level = 3

[profile.dev.package.insta]
opt-level = 3

[profile.dev.package.similar]
opt-level = 3
